version: '3.4'

services:
  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Admin@123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  backend:
    image: ${DOCKER_REGISTRY-}api
    depends_on:
      - sqldata
    ports:
      - "5000:80"
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      DBConnection: "Data Source = sqldata,1433; Initial Catalog = master; Persist Security Info = True; User ID = sa; Password = Admin@123"